### ISSUE TITLE
Google's ASN 15169 crashes irrexplorer

### ISSUE THREAD

**Issue by job** [job/irrexplorer#34]
Do **not** click: hxxp://irrexplorer.nlnog.net/search/15169

Seems google has a lot of IRR objects, nearly 7000:

```
Vurt:~ job$ bgpq3 as15169 | wc -l
    6715
```

Either `irexwww` or browsers in general have trouble with the size of it.

**Comment by htj** [comment]
Pretty easy to re-create. It is postgres tipping over.
This why one should do LIMIT on sql queries :-) Unfortunately, fixing this is not that easy, as putting limit on things will not necessarily get the managed prefixes right (but we might be able to live with this for large queries. I need to re-write some queries to LEFT OUTER JOIN or LATERAL instead of UNION.

**Comment by job** [comment]
This was fixed by b78032d66fa6b33dace73c24432ce8f0038aca3f
