### ISSUE TITLE
Setup instructions are out of date

### ISSUE THREAD

**Issue by dotwaffle** [job/irrexplorer#49]
To recreate:

* Get a fresh clone of the repo.
* `mkvirtualenv irrexplorer`
* `pip install -r requirements.txt`
* `./query 1.2.3.0/24`

```
10:54:14 [dotwaffle@engelbert:~/Code/irrexplorer] [irrexplorer] master ± ./query 1.2.3.0/24
Traceback (most recent call last):
  File "./query", line 47, in <module>
    main()
  File "./query", line 22, in main
    result = report.prefix_report(db, so.value)
AttributeError: 'module' object has no attribute 'prefix_report'
```

Additionally, irr.yml no longer exists in the repo.

**Comment by htj** [comment]
The commands are there are not really enough. You'd need to mirror several IRR repositories as well.

Could you try this diff for the query tool

diff --git a/query b/query
index 314790d..ad0b063 100755
--- a/query
+++ b/query
@@ -19,11 +19,11 @@ def main():
             so = utils.classifySearchString(arg)
 
             if type(so) is utils.Prefix:
-                result = report.prefix_report(db, so.value)
+                result = report.prefix(db, so.value)
                 # prefix report already prints some stuff (consider changing that)
 
             if type(so) is utils.ASNumber:
-                result = report.as_report(db, so.value)
+                result = report.as_prefixes(db, so.value)
                 for prefix, sources in result['prefixes'].items():
                     print prefix, sources.keys()
                 print
@@ -32,7 +32,7 @@ def main():
 
             if type(so) is utils.ASMacro:
                 #res = db.query_as_macro(so.value)
-                result = report.as_macro_report(db, so.value)
+                result = report.macro_expand(db, so.value)
                 for e in result['expanded']:
                     print e
                 print

The web interface is considered the main usage so query tools isn't always up to date :-)

The README no longer references irr.yml, fixed in 94de8520c470f9024c5bba4b61c09aafe7ac1b6c

**Comment by dotwaffle** [comment]
That didn't paste quite as well as you'd have hoped :) Can you gist it and link?

**Comment by htj** [comment]
https://gist.githubusercontent.com/htj/58c54ac5c7d4509345d935db608832e1/raw/f5a6fd38a49e27bce1bac1bac681df48ca9d5e2a/query.diff

**Comment by dotwaffle** [comment]
Thanks, now I get:

```
14:17:00 [dotwaffle@engelbert:~/Code/irrexplorer] [irrexplorer] master(+3/-3) ± ./query 1.2.3.0/24
Prefix report: 1.2.3.0/24
Traceback (most recent call last):
  File "./query", line 47, in <module>
    main()
  File "./query", line 22, in main
    result = report.prefix(db, so.value)
  File "/home/dotwaffle/Code/irrexplorer/irrexplorer/report.py", line 186, in prefix
    routes = pgdb.query_prefix(prefix)
  File "/home/dotwaffle/Code/irrexplorer/irrexplorer/sqldb.py", line 66, in query_prefix
    return self._execute_fetchall(query, (prefix,))
  File "/home/dotwaffle/Code/irrexplorer/irrexplorer/sqldb.py", line 52, in _execute_fetchall
    cur = self._get_cursor()
  File "/home/dotwaffle/Code/irrexplorer/irrexplorer/sqldb.py", line 46, in _get_cursor
    self.conn = psycopg2.connect("dbname=irrexplorer user=irrexplorer")
  File "/home/dotwaffle/.virtualenvs/irrexplorer/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "irrexplorer"
```
I haven't gotten around to setting up postgres yet though, so I'll assume we're good for now!
