### ISSUE TITLE
Confusing results 

### ISSUE THREAD

**Issue by devicenull** [job/irrexplorer#51]
This briefly confused us.  We searched for 144.202.0.0/17, and got these results:

<img width="764" alt="2018-02-05 16_07_46-irrexplorer nlnog net_search_144 202 0 0_17" src="https://user-images.githubusercontent.com/58017/35828870-13e240b4-0a8f-11e8-87fa-7abdfe65f6bc.png">

It looks like it went up a level to the /16, then back down to the *next* /17?

(attached a screenshot because we're already working on cleaning up the incorrect /16)

**Comment by htj** [comment]
This is intentional, but I can see why it is confusing.

First, all prefixes overlapping the IP/prefix is found. Then all overlapping prefixes to that set is found.

I can remember discussing this with Job when we wrote it, but I cannot remember exactly why we made it like this. But it convenient to see the prefixes next another prefix.

**Comment by devicenull** [comment]
I can understand why you'd want to see prefixes like this.

Perhaps the rows that aren't within the prefix that was entered could have a different background color?

**Comment by job** [comment]
it was considered a feature to show related prefixes, many people are not aware of overlapping route-objects - but you are right that irrexplorer would be better if there is visual aids to highlight what you searched for and what you got back. 

@devicenull patches are welcome!!! :-)
